# See http://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v2.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: requirements-txt-fixer
    -   id: flake8
    -   id: pretty-format-json

-   repo: https://github.com/FalconSocial/pre-commit-python-sorter
    sha: master
    hooks:
    -   id: python-import-sorter
        args: ['--silent-overwrite']
